DatabaseDirectoryPath: C:\Dor\MyProjects\TasksManager\TaskManager\Repository\Database.JsonService\database
NotesDirectoryPath: C:\Dor\MyProjects\TasksManager\TaskManager\Repository\Database.JsonService\notes
NotesTasksDirectoryPath: C:\Dor\MyProjects\TasksManager\TaskManager\Repository\Database.JsonService\tasks
DefaultTasksGroup: Bugs-104