DatabaseDirectoryPath: C:\Dor\Apps\DorTasker\db
NotesDirectoryPath: C:\Users\Dor.Shaar.CORP\OneDrive - Votiro\Dor\Notes
NotesTasksDirectoryPath: C:\Users\Dor.Shaar.CORP\OneDrive - Votiro\Dor\Notes\tasks
DefaultTasksGroup: bugs-150