database:
     directory_path: C:\Dor\MyProjects\TasksManager\TaskManager\Repository\Database.JsonService\database
     notes_path: C:\Users\dor.shaar\OneDrive - Votiro\Dor\Lectures and Info\Work\Notes