DatabaseDirectoryPath: C:\Users\Public\DorShaar\C#Work\TaskManagerApp\TaskerStorage\DorShaarHome\database
NotesDirectoryPath: C:\Users\Public\DorShaar\C#Work\TaskManagerApp\TaskerStorage\DorShaarHome\general_notes
NotesTasksDirectoryPath: C:\Users\Public\DorShaar\C#Work\TaskManagerApp\TaskerStorage\DorShaarHome\tasks
DefaultTasksGroup: