database:
     directory_path: C:\Users\dor.shaar\TaskManagerApp\database
     notes_path: C:\Users\dor.shaar\OneDrive - Votiro\Dor\Notes
     tasks_notes_path: C:\Users\dor.shaar\OneDrive - Votiro\Dor\Notes\tasks