database:
     DatabaseDirectoryPath: C:\Users\dor.shaar\TaskManagerApp\database
     NotesDirectoryPath: C:\Users\dor.shaar\OneDrive - Votiro\Dor\Notes
     NotesTasksDirectoryPath: C:\Users\dor.shaar\OneDrive - Votiro\Dor\Notes\tasks