database:
     directory_path: C:\Users\Dor Shaar\TaskManagerApp\db\
     notes_path: C:\Users\dor.shaar\OneDrive - Votiro\Dor\Lectures and Info\Work\Notes
     tasks_notes_path: C:\Users\dor.shaar\OneDrive - Votiro\Dor\Lectures and Info\Work\Notes\tasks