DatabaseDirectoryPath: C:\Users\Dor Shaar\TaskManagerApp\db
NotesDirectoryPath: C:\Dor\My Computing Programs\DevWorld
NotesTasksDirectoryPath: C:\Dor\My Computing Programs\DevWorld\Tasks
DefaultTasksGroup: Learning-Computer-Vision